### PR TITLE
Update requests to version 1.1.0

### PR DESCRIPTION
**Pull request by vially**

### CODE REVIEW

**Comment by beenje** [comment]
Thanks for the update.
Is there a new feature you need in that version?

**Comment by vially** [comment]
I'm working on a Google Music addon for XBMC which uses the [Unofficial-Google-Music-API](https://github.com/simon-weber/Unofficial-Google-Music-API) and the latest version of this API needs requests 1.1.0 (at least that's what it says in it's requirements).

**Comment by beenje** [comment]
I just pushed the new version to the official repo.

**Comment by vially** [comment]
Great! Thanks. 

Although I still have to wait for [mutagen](https://github.com/Giftie/script.module.mutagen/pull/1) to be updated as well before I can push my version to the repo.

**Pull request merged**
