### PR TITLE
[utils] winreg module may not exist like on windows-uwp platfrom

### PR DESCRIPTION
**Pull request by afedchin**

### CODE REVIEW

**Comment by beenje** [comment]
This repo is just to package the official requests library.

It looks like this issue should be fixed upstream.
Could you submit it there instead? https://github.com/requests/requests/issues

**Comment by afedchin** [comment]
ok

**Comment by MartijnKaijser** [comment]
The fixes was merged upstream however there's no tagged version yet. Perhaps we can do a RC update to our repo so at least we have the fixed version for UWP?

**Comment by MartijnKaijser** [comment]
Added temp version to our Leia repo here https://github.com/xbmc/repo-scripts/commit/1d1c10b32c2e6d9e9492627da7b7e69110f58cc1

Once a new version is tagged please update it in the normal repo branch and we can remove the temp one from leia repo.

**Comment by beenje** [comment]
Thanks @MartijnKaijser 
I was indeed waiting for a new official release from requests.
Will do the update when it's available.

**Comment by MartijnKaijser** [comment]
We could always ask  if they want to tag a version however this temp solution works just fine. At least we can continue testing UWP. Already hitting other limitations with other modules that need to be solved upstream.

**Pull request closed without merging**
