### PR TITLE
Bumped request version to 2.12.4

### PR DESCRIPTION
**Pull request by razzeee**

### CODE REVIEW

**Comment by beenje** [comment]
Thanks for the pull request.
Could you just remove all the *.pyo files?
You could add '*.pyo' to .gitignore to avoid committing them by mistake.

**Comment by razzeee** [comment]
Sorry, should have checked that.

Updated PR.
Added to gitignore and removed.

**Comment by beenje** [comment]
If I do a quick diff with requests 2.12.4, I have this file missing in your branch:
lib/requests/packages/urllib3/contrib/pyopenssl.py
Can you check?

**Comment by razzeee** [comment]
Weird, maybe I've killed it by accident, when removing the *.pyo files. Should be there now.

**Comment by beenje** [comment]
pyopenssl.py starts with "pyo", so yes I guess you did.
I still don't see the file...

**Comment by razzeee** [comment]
Should be there now, sorry, git was a bit stubborn.

**Comment by beenje** [comment]
It often is :-)
Thanks!

**Comment by razzeee** [comment]
No hurry, but will you push it to the official repo in time?

And thanks for maintaining this.

**Comment by beenje** [comment]
I just pushed!

**Comment by razzeee** [comment]
Sorry, I ment to the official kodi repo :)
https://github.com/xbmc/repo-scripts/pulls

Edit: Sorry, wasn't aware that you can push directly

**Pull request merged**
