### PR TITLE
Update requests to 2.21.0

### PR DESCRIPTION
**Pull request by Freso**
Based on `requests-2.21.0.tar.gz` from PyPI: https://pypi.org/project/requests/#files

The .tar.gz from PyPI doesn’t include a number of files I assume have been taken from GitHub previously. I chose to not bring them back in as these are the files that you would get from `pip install requests`, which I guess is what this add‐on tries to emulate?

(I would have made this request against the `leia` branch, but I guess there is no such yet. :))

### CODE REVIEW

**Comment by beenje** [comment]
Thanks for the PR. I don't use Kodi much anymore. Are you interested in taking over the maintenance of this repository (and its dependencies)?

**Comment by Freso** [comment]
I’d be interested in that, yes, sure. :)

**Comment by beenje** [comment]
Great. Could I suggest that you submit this new version directly to the official add-on repository then?
You can refer to this PR to mention you are the new maintainer.

**Comment by Freso** [comment]
Yes, absolutely. I already have one pending PR waiting. :) Can you give me push access? And maybe admin access so I can transfer the repository to @Freso (so PR/issue history etc. is kept)?

**Comment by beenje** [comment]
I added you as collaborator. I tried transferring the repo but got the error: "Freso/script.module.requests already exists"
According to the [documentation](https://help.github.com/en/articles/transferring-a-repository):
> The target account must not have a repository with the same name, or a fork in the same network.

So it looks like you have to delete your fork before I can transfer it.

**Comment by Freso** [comment]
Yeah. I wanted to merge in this commit before deleting my own repository, to prevent any weird behaviour in this PR. :)

**Comment by Freso** [comment]
And Freso/script.module.requests is gone!

**Comment by beenje** [comment]
Do you want me to transfer the requests and idna repositories right away? Or should I wait for your PR to be merged in the official add-on repo?

**Comment by Freso** [comment]
Go ahead and transfer. GitHub will redirect any links. :)

**Comment by Freso** [comment]
I also think you may need to retransfer the other ones. I’m getting messages that the transfers expired… but GH is also generally acting weird, so maybe I just need to leave it for tonight and return to it in the morning.

**Comment by beenje** [comment]
I saw that the other repositories have been transferred. I just sent the request for requests and idna.
Thanks for taking over! Have fun :-)

**Pull request merged**
